name: Pull request
on: [push,pull_request]

jobs:
  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run ShellCheck
        uses: azohra/shell-linter@v0.6.0
        with:
          exclude-paths:
            - Dockerfile
            - .github/CODEOWNERS
            - .github/ISSUE_TEMPLATE
